openapi: 3.0.1
info:
  title: Conditional Access Policy API
  version: "1.0.0"
servers:
  - url: https://graph.microsoft.com/v1.0
paths:
  /identity/conditionalAccess/policies:
    get:
      summary: Get Conditional Access Policies
      description: Returns Conditional Access policies with id, displayName, createdDateTime, and modifiedDateTime
      operationId: getConditionalAccessPolicies
      parameters:
        - in: header
          name: ConsistencyLevel
          schema:
            type: string
            enum:
              - eventual
          required: true
          description: Required for advanced queries and using $count on directory objects
        - in: query
          name: $count
          schema:
            type: boolean
          description: Include total count of objects
        - in: query
          name: $top
          schema:
            type: integer
            minimum: 1
            maximum: 999
          description: Number of items to return (page size)
        - in: query
          name: $skip
          schema:
            type: integer
            minimum: 0
          description: Number of items to skip (for paging)
      responses:
        '200':
          description: A list of Conditional Access Policies
          content:
            application/json:
              schema:
                type: object
                properties:
                  value:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        displayName:
                          type: string
                        createdDateTime:
                          type: string
                          format: date-time
                        modifiedDateTime:
                          type: string
                          format: date-time
                          nullable: true
                  "@odata.count":
                    type: integer
                    description: Total count of objects (if $count=true)
                  "@odata.nextLink":
                    type: string
                    description: Link to next page of results, if more results available
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
